name: CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: make install
      - run: make lint
      - run: make test

  integration_postgres:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Gate integration tests
        id: gate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -n "${DATABASE_URL}" ]; then
            echo "enabled=true" >> "$GITHUB_OUTPUT"
          else
            echo "enabled=false" >> "$GITHUB_OUTPUT"
            echo "No DATABASE_URL; skipping integration tests."
          fi

      - uses: actions/checkout@v4
        if: steps.gate.outputs.enabled == 'true'

      - uses: actions/setup-python@v6
        if: steps.gate.outputs.enabled == 'true'
        with:
          python-version: '3.12'
          cache: 'pip'

      - run: make install
        if: steps.gate.outputs.enabled == 'true'

      - name: Run integration tests
        if: steps.gate.outputs.enabled == 'true'
        run: make test-integration
