name: Release
on:
  push:
    tags: ['v*']        # triggers on v0.1.0 etc.
  workflow_dispatch:     # allow manual test runs

permissions:
  contents: write
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    # simple and template-friendly: run on any tag
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    env:
      # optional; empty when not set, safe for 'if:' checks
      SENTRY_DSN: ${{ secrets.SENTRY_DSN || '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Compute image name (lowercase)
        id: img
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "image=ghcr.io/${REPO_LC}" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build
        run: |
          docker build \
            -t ${{ steps.img.outputs.image }}:${{ github.ref_name }} \
            -t ${{ steps.img.outputs.image }}:latest .

      - name: Smoke test container health
        run: |
          cid=$(docker run -d -p 8000:8000 ${{ steps.img.outputs.image }}:latest)
          for i in {1..30}; do curl -fsS http://localhost:8000/health && break || sleep 1; done
          docker logs "$cid" --tail 50
          docker rm -f "$cid"

      - name: Push
        run: |
          docker push ${{ steps.img.outputs.image }}:${{ github.ref_name }}
          docker push ${{ steps.img.outputs.image }}:latest

      - name: Sentry release (optional)
        if: ${{ env.SENTRY_DSN != '' }}
        run: echo "Would run sentry-cli here for ${{ github.ref_name }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            See CHANGELOG.md for details.
            Image:
            - ${{ steps.img.outputs.image }}:latest
            - ${{ steps.img.outputs.image }}:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
